# Gaps & borders
gaps inner 13
gaps outer 7
default_border pixel 3px
default_floating_border pixel 3px

# SwayFX (requires SwayFX)
blur enable
blur_passes 2
blur_radius 5
blur_noise 0
corner_radius 6

# Waybar layer effects
layer_effects "waybar" {
    blur enable;
    blur_xray enable;
    blur_ignore_transparent enable;
    shadows enable;
}

# Colors
#                     border   bg       text     ind      child
client.focused          #d8cab8 #141216 #d8cab8 #d8cab8  #d8cab8
client.focused_inactive #7a53e8 #141216 #d8cab8 #7a53e8  #7a53e8
client.unfocused        #7a53e8 #141216 #d8cab8 #7a53e8  #7a53e8
client.urgent           #fcb167 #141216 #d8cab8 #fcb167  #fcb167
client.placeholder      #7a53e8 #141216 #d8cab8 #7a53e8  #7a53e8
