# Switch to workspace
# Left monitor
bindsym $mod+a workspace "auth"
bindsym $mod+r workspace "reference"
bindsym $mod+n workspace "notes"
bindsym $mod+q workspace "later"

# Middle monitor
bindsym $mod+x workspace "research"
bindsym $mod+b workspace "browse"
bindsym $mod+v workspace "video"
bindsym $mod+z workspace "vm"
bindsym $mod+t workspace "terminal"
bindsym $mod+c workspace "code"
bindsym $mod+w workspace "write"
bindsym $mod+g workspace "game"

# Right monitor
bindsym $mod+u workspace "music"
bindsym $mod+m workspace "messages"

# Numbered catch-alls (middle monitor)
bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+4 workspace number 4
bindsym $mod+5 workspace number 5
bindsym $mod+6 workspace number 6
bindsym $mod+7 workspace number 7
bindsym $mod+8 workspace number 8
bindsym $mod+9 workspace number 9
bindsym $mod+0 workspace number 10

# Move focused container to workspace
# Left
bindsym $mod+Shift+a move container to workspace "auth"
bindsym $mod+Shift+r move container to workspace "reference"
bindsym $mod+Shift+n move container to workspace "notes"
bindsym $mod+Shift+q move container to workspace "later"

# Middle
bindsym $mod+Shift+x move container to workspace "research"
bindsym $mod+Shift+b move container to workspace "browse"
bindsym $mod+Shift+v move container to workspace "video"
bindsym $mod+Shift+z move container to workspace "vm"
bindsym $mod+Shift+t move container to workspace "terminal"
bindsym $mod+Shift+c move container to workspace "code"
bindsym $mod+Shift+w move container to workspace "write"
bindsym $mod+Shift+g move container to workspace "game"

# Right
bindsym $mod+Shift+u move container to workspace "music"
bindsym $mod+Shift+m move container to workspace "messages"

# Numbered catch-alls (middle monitor)
bindsym $mod+Shift+1 move container to workspace number 1
bindsym $mod+Shift+2 move container to workspace number 2
bindsym $mod+Shift+3 move container to workspace number 3
bindsym $mod+Shift+4 move container to workspace number 4
bindsym $mod+Shift+5 move container to workspace number 5
bindsym $mod+Shift+6 move container to workspace number 6
bindsym $mod+Shift+7 move container to workspace number 7
bindsym $mod+Shift+8 move container to workspace number 8
bindsym $mod+Shift+9 move container to workspace number 9
bindsym $mod+Shift+0 move container to workspace number 10

# Move workspace across outputs
bindsym $mod+greater move workspace to output right   # Win+Shift+comma
bindsym $mod+less    move workspace to output left    # Win+Shift+period
