# Switch to workspace
# Left monitor
bindsym $mod+a workspace "left"
bindsym $mod+r workspace "ref"
bindsym $mod+b workspace "brws"

# Middle monitor
bindsym $mod+s workspace "midl"
bindsym $mod+n workspace "note"
bindsym $mod+v workspace "code"
bindsym $mod+x workspace "rsrch"
bindsym $mod+z workspace "vm"
bindsym $mod+w workspace "wtch"

# Right monitor
bindsym $mod+d workspace "rght"
bindsym $mod+c workspace "chat"
bindsym $mod+t workspace "llm"

# Move focused container to workspace
# Left
bindsym $mod+Shift+a move container to workspace "left"
bindsym $mod+Shift+r move container to workspace "ref"
bindsym $mod+Shift+b move container to workspace "brws"

# Middle
bindsym $mod+Shift+s move container to workspace "midl"
bindsym $mod+Shift+n move container to workspace "note"
bindsym $mod+Shift+v move container to workspace "code"
bindsym $mod+Shift+x move container to workspace "rsrch"
bindsym $mod+Shift+z move container to workspace "vm"
bindsym $mod+Shift+w move container to workspace "wtch"

# Right
bindsym $mod+Shift+d move container to workspace "rght"
bindsym $mod+Shift+c move container to workspace "chat"
bindsym $mod+Shift+t move container to workspace "llm"

# Move workspace across outputs
bindsym $mod+greater move workspace to output right   # Win+Shift+comma
bindsym $mod+less    move workspace to output left    # Win+Shift+period
